export type ChargeStatus = "succeeded" | "refunded";
export type PaymentMethod =
  | "visa"
  | "mastercard"
  | "paynow"
  | "paynow_transfer"
  | "cash";

export interface Charge {
  id: string;
  date: string;
  customer: string;
  chargeId: string;
  amount: number;
  fees: number;
  netAmount: number;
  currency: string;
  method: PaymentMethod;
  cardLast4?: string;
  status: ChargeStatus;
  staff: string;
}

export const charges: Charge[] = [
  {
    id: "c1",
    date: "May 07 17:01:52",
    customer: "nitinmuthyala+01@gmail...",
    chargeId: "#a1b8a705-adcb-...",
    amount: 0.79,
    fees: 0.52,
    netAmount: 0.27,
    currency: "SGD",
    method: "visa",
    cardLast4: "3271",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c2",
    date: "May 06 23:32:21",
    customer: "nitinmuthyala+01@gmail...",
    chargeId: "#a1b72e41-1e56-...",
    amount: 0.7,
    fees: 0.01,
    netAmount: 0.69,
    currency: "SGD",
    method: "paynow",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c3",
    date: "May 06 23:27:38",
    customer: "nitinmuthyala+01@gmail...",
    chargeId: "#a1b72dec-bfa9-...",
    amount: 0.77,
    fees: 0.52,
    netAmount: 0.25,
    currency: "SGD",
    method: "visa",
    cardLast4: "3271",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c4",
    date: "May 06 13:25:31",
    customer: "N/A",
    chargeId: "#a1b656d8-7f5f-...",
    amount: 1472.78,
    fees: 0.0,
    netAmount: 1472.78,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "son nguyen",
  },
  {
    id: "c5",
    date: "May 06 13:24:47",
    customer: "N/A",
    chargeId: "#a1b65695-c711-...",
    amount: 1472.78,
    fees: 0.0,
    netAmount: 1472.78,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "son nguyen",
  },
  {
    id: "c6",
    date: "May 06 13:14:40",
    customer: "N/A",
    chargeId: "#a1b652f7-4824-...",
    amount: 50.87,
    fees: 0.0,
    netAmount: 50.87,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "son nguyen",
  },
  {
    id: "c7",
    date: "May 05 17:01:13",
    customer: "N/A",
    chargeId: "#a1b4a100-9a28-...",
    amount: 1429.72,
    fees: 0.0,
    netAmount: 1429.72,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "Reuben Choo",
  },
  {
    id: "c8",
    date: "May 05 16:59:50",
    customer: "N/A",
    chargeId: "#a1b4a081-8938-...",
    amount: 2544.15,
    fees: 0.0,
    netAmount: 2544.15,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "Reuben Choo",
  },
  {
    id: "c9",
    date: "May 05 16:59:07",
    customer: "N/A",
    chargeId: "#a1b4a040-16cd-...",
    amount: 1429.72,
    fees: 0.0,
    netAmount: 1429.72,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "Reuben Choo",
  },
  {
    id: "c10",
    date: "May 04 23:22:37",
    customer: "nitinmuthyala+01@gmail...",
    chargeId: "#a1b3263b-c3e5-...",
    amount: 0.86,
    fees: 0.01,
    netAmount: 0.85,
    currency: "SGD",
    method: "paynow",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c11",
    date: "Apr 30 14:04:02",
    customer: "N/A",
    chargeId: "#a1aa52b6-aa49-...",
    amount: 0.3,
    fees: 0.0,
    netAmount: 0.3,
    currency: "SGD",
    method: "paynow_transfer",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c12",
    date: "Apr 30 13:59:41",
    customer: "N/A",
    chargeId: "#a1aa5129-541e-...",
    amount: 0.65,
    fees: 0.0,
    netAmount: 0.65,
    currency: "SGD",
    method: "paynow_transfer",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c13",
    date: "Apr 30 13:58:42",
    customer: "N/A",
    chargeId: "#a1aa50cf-9cbb-...",
    amount: 0.45,
    fees: 0.0,
    netAmount: 0.45,
    currency: "SGD",
    method: "paynow_transfer",
    status: "succeeded",
    staff: "N/A",
  },
  {
    id: "c14",
    date: "Apr 21 14:48:32",
    customer: "N/A",
    chargeId: "#a19847c6-3171-...",
    amount: 29.97,
    fees: 0.0,
    netAmount: 29.97,
    currency: "SGD",
    method: "cash",
    status: "succeeded",
    staff: "Hannah Curay",
  },
  {
    id: "c15",
    date: "Apr 16 11:50:38",
    customer: "raymond@hit-pay.com",
    chargeId: "#a18de85e-0542-...",
    amount: 1.03,
    fees: 0.53,
    netAmount: 0.5,
    currency: "SGD",
    method: "mastercard",
    cardLast4: "4090",
    status: "refunded",
    staff: "Reuben Choo",
  },
  {
    id: "c16",
    date: "Apr 16 00:34:10",
    customer: "nitinmuthyala@gmail.com",
    chargeId: "#a18d070b-b61b-...",
    amount: 0.62,
    fees: 0.01,
    netAmount: 0.61,
    currency: "SGD",
    method: "paynow",
    status: "succeeded",
    staff: "N/A",
  },
];
